volumes:
  db:
    driver: local
  opensearch-data:
     driver: local

networks:
  opensearch-net:

services:
  # docker run --name local-mysql -e MYSQL_ROOT_PASSWORD=ecompwd#24 -d -p 3306:3306 mysql:latest
  # docker start local-mysql
  # docker stop local-mysql
  # docker run -it --network local-network --rm mysql mysql -hlocal-mysql -uexample-user -p

  #  docker exec -it local-mysql /bin/bash

  # USER="root"
  # PASS="ecompwd#24"
  mysql:
    image: mysql:latest
    container_name: local-mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=ecom
      - MYSQL_ROOT_PASSWORD=ecompwd#24
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


  #  docker run --name local-redis -p 6379:6379 -d redis:7.4.0-alpine
  #  docker start local-redis
  #  docker start local-redis
  #  docker exec -it local-redis redis-cli
  redis:
    image: redis:7.4.0-alpine
    container_name: local-redis
    cap_add:
      - SYS_NICE
    #restart: always
    environment:
      DEBUG: "true"
    ports:
      - '6379:6379'  

  # docker run --name local-kafka  -p 9092:9092 -d  apache/kafka:latest
  # docker stop local-kafka
  # docker start local-kafka
  # docker exec --workdir /opt/kafka/bin/ -it local-kafka sh
  
  kafka:
    image: apache/kafka:latest
    container_name: local-kafka
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.001'
    #      memory: 50M
    #    reservations:
    #      cpus: '0.0001'
    #      memory: 20M
    cap_add:
      - SYS_NICE
    #restart: always
    environment:
      DEBUG: "true"
    ports:
      - '9092:9092'
    

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: local-opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true  # along with the memlock settings below, disables swapping
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ecompwd#24    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and higher
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536  # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600  # required for Performance Analyzer
    networks:
      - opensearch-net

  opensearch-ui:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: local-opensearch-ui
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://local-opensearch:9200"]'
    networks:
      - opensearch-net